// <auto-generated />
using System;
using Liikunta.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Liikunta.Migrations
{
    [DbContext(typeof(LiikuntaContext))]
    [Migration("20230523222617_Jiji")]
    partial class Jiji
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Liikunta.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FID")
                        .HasColumnType("int");

                    b.Property<int?>("Kapasiteet")
                        .HasColumnType("int");

                    b.Property<string>("Kaupunki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operaattor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Osoite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("x")
                        .HasColumnType("float");

                    b.Property<double?>("y")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FID");

                    b.ToTable("City");
                });

            modelBuilder.Entity("Liikunta.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoveredDistanceM")
                        .HasColumnType("int");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartureStationId")
                        .HasColumnType("int");

                    b.Property<string>("DepartureStationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationSec")
                        .HasColumnType("int");

                    b.Property<DateTime>("Return")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReturnStationId")
                        .HasColumnType("int");

                    b.Property<string>("ReturnStationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("Liikunta.Models.City", b =>
                {
                    b.HasOne("Liikunta.Models.Route", null)
                        .WithMany("Cities")
                        .HasForeignKey("FID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Liikunta.Models.Route", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
